services:
  php_app:
    image: php:8.4-fpm-alpine
    container_name: php_app
    volumes:
      - .:/app
    networks:
      - fastcgi
      - db

  database_app:
    image: mysql:8.0
    container_name: database_app
    networks:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/mysql
      - certs:/etc/certs
    ports:
      - "3306:3306"
    command: [ "mysqld",
               "--character-set-server=utf8mb4",
               "--collation-server=utf8mb4_unicode_ci",
               "--bind-address=0.0.0.0",
               "--require_secure_transport=ON",
               "--ssl-ca=/etc/certs/ca-cert.pem",
               "--ssl-cert=/etc/certs/server-cert.pem",
               "--ssl-key=/etc/certs/server-key.pem",
               "--default_authentication_plugin=mysql_native_password" ]

volumes:
  db_data:

networks:
  fastcgi:
  db:
